
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */
public class Department extends javax.swing.JFrame {

    /**
     * Creates new form Department
     */
    Connection con=null; 
    public Department() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deptid = new javax.swing.JTextField();
        deptname = new javax.swing.JTextField();
        buildingno = new javax.swing.JTextField();
        buildingname = new javax.swing.JTextField();
        campus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewBill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("deptid");

        jLabel2.setText("deptname");

        jLabel3.setText("building no");

        jLabel4.setText("building name");

        jLabel5.setText("campus");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Department");

        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        view.setText("View All Department");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        viewBill.setText("View Bill");
        viewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(insert))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deptid)
                                    .addComponent(deptname)
                                    .addComponent(buildingno)
                                    .addComponent(buildingname)
                                    .addComponent(campus)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(delete)))
                                .addGap(54, 54, 54)
                                .addComponent(close))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(view)
                                .addGap(47, 47, 47)
                                .addComponent(viewBill))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buildingno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buildingname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(close))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view)
                    .addComponent(viewBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        int r=0,r1=0;
        try{
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(deptid.getText().trim().length()>0 &&deptname.getText().trim().length()>0 &&buildingname.getText().trim().length()>0 &&buildingno.getText().trim().length()>0 &&campus.getText().trim().length()>0)
            {
            PreparedStatement p=con.prepareStatement("insert into department(deptid,deptname,buildingno,buildingname,campus) values(?,?,?,?,?);");
            p.setString(1,deptid.getText().trim());
            p.setString(2,deptname.getText().trim());
            p.setString(3,buildingno.getText().trim());
            p.setString(4,buildingname.getText().trim());
            p.setString(5,campus.getText().trim());
             r=p.executeUpdate();
            //insert into department entry bill table
            PreparedStatement p1=con.prepareStatement("insert into bill(deptid,amount) values(?,0);");
            p1.setString(1,deptid.getText().trim());
             r1=p1.executeUpdate();
            }
            else{
                JOptionPane.showMessageDialog(null,"form not properly filled");
            }
            if(r>0&&r1>0)
            JOptionPane.showMessageDialog(null, "Successfull Insert");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int r=0;
         try{
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(deptid.getText().trim().length()>0 &&deptname.getText().trim().length()>0 &&buildingname.getText().trim().length()>0 &&buildingno.getText().trim().length()>0 &&campus.getText().trim().length()>0)
            {
            PreparedStatement p=con.prepareStatement("update department set deptname=?,buildingno=?,buildingname=?,campus=? where deptid=?;");
            p.setString(5,deptid.getText().trim());
            p.setString(1,deptname.getText().trim());
            p.setString(2,buildingno.getText().trim());
            p.setString(3,buildingname.getText().trim());
            p.setString(4,campus.getText().trim());
            r=p.executeUpdate();
            }
            else{
                JOptionPane.showMessageDialog(null,"form not properly filled");
            }
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull update");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            PreparedStatement p=con.prepareStatement("delete from department where deptid=?;");
            p.setString(1,deptid.getText().trim());
            int r=p.executeUpdate();
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull delete");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from department");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void viewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from bill");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buildingname;
    private javax.swing.JTextField buildingno;
    private javax.swing.JTextField campus;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deptid;
    private javax.swing.JTextField deptname;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    private javax.swing.JButton viewBill;
    // End of variables declaration//GEN-END:variables
}
