
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import static javafx.scene.paint.Color.color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */
public class ReservationForm extends javax.swing.JFrame {

    /**
     * Creates new form ReservationForm
     */
    Connection con=null;
    JComboBox jComboBox1=null; 
    public ReservationForm() {
         try{
            jComboBox1=new JComboBox();
            jComboBox1.setBounds(230, 480, 175, 25);
        jComboBox1.addItem("DeptID");
        jComboBox1.addItem("Booking Date");
        add(jComboBox1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        formno = new javax.swing.JTextField();
        staffid = new javax.swing.JTextField();
        deptid = new javax.swing.JTextField();
        vehicleno = new javax.swing.JTextField();
        bookingdate = new javax.swing.JTextField();
        bookingtime = new javax.swing.JTextField();
        destination = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        driverstaffid = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        viewRegisteredform = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        close = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        viewDriverdetail = new javax.swing.JButton();
        viewVehicledetail = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form No");

        jLabel2.setText("Staff ID");

        jLabel3.setText("Dept ID");

        jLabel4.setText("Vehicle No");

        jLabel5.setText("Booking Date");

        jLabel6.setText("Booking Time");

        jLabel7.setText("Destination");

        jLabel8.setText("Purpose");

        jLabel9.setText("Driver Staff ID");

        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        viewRegisteredform.setText("view registered forms");
        viewRegisteredform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegisteredformActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Reservation Form");

        viewDriverdetail.setText("view driver details ");
        viewDriverdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDriverdetailActionPerformed(evt);
            }
        });

        viewVehicledetail.setText("view vehicle detail");
        viewVehicledetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVehicledetailActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel11.setText("format yyyy-mm-dd");

        jLabel12.setText("format hh:mm:ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewDriverdetail)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(insert)
                                .addGap(26, 26, 26)
                                .addComponent(update)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewVehicledetail)
                        .addGap(130, 130, 130)
                        .addComponent(search))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bookingdate)
                                        .addComponent(bookingtime)
                                        .addComponent(destination)
                                        .addComponent(purpose)
                                        .addComponent(driverstaffid)
                                        .addComponent(vehicleno, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                    .addComponent(formno)
                                    .addComponent(staffid)
                                    .addComponent(deptid))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(159, 159, 159))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(viewRegisteredform)
                                .addGap(70, 70, 70)
                                .addComponent(delete)
                                .addGap(73, 73, 73)))
                        .addComponent(close)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deptid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bookingdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bookingtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(driverstaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(update)
                    .addComponent(viewRegisteredform)
                    .addComponent(delete)
                    .addComponent(close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDriverdetail)
                    .addComponent(viewVehicledetail)
                    .addComponent(search))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
         try{int r=0,r1=0;
            String s=""; 
            con=MySqlConnect.ConnectDB();
            //check vehicle availability
            PreparedStatement pchk=con.prepareStatement("Select * from vehicle where registrationno=?;");
            pchk.setString(1, vehicleno.getText().trim());
            ResultSet rs=pchk.executeQuery();
            if(rs.next())
            {
                s=rs.getString("booked");
            }
            //check driverstaff or not
            PreparedStatement pchk1=con.prepareStatement("Select * from staffdriver where staffid=?;");
            pchk1.setString(1, driverstaffid.getText().trim());
            ResultSet rs1=pchk1.executeQuery();
         
            if(s.equalsIgnoreCase("0")&& rs1.next())
            {
            if(formno.getText().trim().length()>0&&staffid.getText().trim().length()>0&&deptid.getText().trim().length()>0&&vehicleno.getText().trim().length()>0&&bookingdate.getText().trim().length()>0&&bookingtime.getText().trim().length()>0&&destination.getText().trim().length()>0&&purpose.getText().trim().length()>0&&driverstaffid.getText().trim().length()>0)
            {
                //insert into reservevehicle
            PreparedStatement p=con.prepareStatement("insert into reservevehicle(formno,staffid,deptid,vehicleno,bookingdate,bookingtime,destination,purpose,driverstaffid) values(?,?,?,?,?,?,?,?,?);");
            p.setString(1,formno.getText().trim());
            p.setString(2,staffid.getText().trim());
            p.setString(3,deptid.getText().trim());
            p.setString(4,vehicleno.getText().trim());
            p.setString(5,bookingdate.getText().trim());
            p.setString(6,bookingtime.getText().trim());
            p.setString(7,destination.getText().trim());
            p.setString(8,purpose.getText().trim());
            p.setString(9,driverstaffid.getText().trim());
            r=p.executeUpdate();
             //update booked status of vehicle
             PreparedStatement p1=con.prepareStatement("update vehicle set booked=? where registrationno=?;");
             p1.setString(1,"1");
             p1.setString(2,vehicleno.getText().trim());
            r1=p1.executeUpdate();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Recheck form");
            }
            if(r>0&&r1>0)
            JOptionPane.showMessageDialog(null, "Successfull Insert");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vehicle not Available or Driver detail mismatch");
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{int r=0,r1=0;
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(formno.getText().trim().length()>0&&staffid.getText().trim().length()>0&&deptid.getText().trim().length()>0&&vehicleno.getText().trim().length()>0&&bookingdate.getText().trim().length()>0&&bookingtime.getText().trim().length()>0&&destination.getText().trim().length()>0&&purpose.getText().trim().length()>0&&driverstaffid.getText().trim().length()>0)
            {      
            PreparedStatement p=con.prepareStatement("update reservevehicle set staffid=?,deptid=?,vehicleno=?,bookingdate=?,bookingtime=?,destination=?,purpose=?,driverstaffid=? where formno=?;");
            p.setString(9,formno.getText().trim());
            p.setString(1,staffid.getText().trim());
            p.setString(2,deptid.getText().trim());
            p.setString(3,vehicleno.getText().trim());
            p.setString(4,bookingdate.getText().trim());
            p.setString(5,bookingtime.getText().trim());
            p.setString(6,destination.getText().trim());
            p.setString(7,purpose.getText().trim());
            p.setString(8,driverstaffid.getText().trim());
            r=p.executeUpdate();
            //update veghicle
            PreparedStatement p1=con.prepareStatement("update vehicle set booked=? where registrationno=?;");
             p1.setString(1,"1");
             p1.setString(2,vehicleno.getText().trim());
            r1=p1.executeUpdate();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Recheck form");
            }
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull update");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void viewRegisteredformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegisteredformActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from reservevehicle;");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewRegisteredformActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
                 try{int r=0,r1=0;
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(formno.getText().trim().length()>0)
            {      
            PreparedStatement p=con.prepareStatement("delete from reservevehicle where formno=?;");
            p.setString(1,formno.getText().trim());
            r=p.executeUpdate();
            }
            //update veghicle
            if(vehicleno.getText().trim().length()>0)
            {
            PreparedStatement p1=con.prepareStatement("update vehicle set booked=? where registrationno=?;");
             p1.setString(1,"0");
             p1.setString(2,vehicleno.getText().trim());
            r1=p1.executeUpdate();
            }
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull delete");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void viewDriverdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDriverdetailActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from staffdriver;");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewDriverdetailActionPerformed

    private void viewVehicledetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVehicledetailActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from vehicle;");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewVehicledetailActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
            PreparedStatement p=null;
        if(jComboBox1.getSelectedItem().equals("DeptID")&& deptid.getText().trim().length()>0)
        {
                    p=con.prepareStatement("Select * from reservevehicle where deptid=?;");
                    p.setString(1, deptid.getText().trim());
        }
        else if(jComboBox1.getSelectedItem().equals("Booking Date")&& bookingdate.getText().trim().length()>0)
        {
                    p=con.prepareStatement("Select * from reservevehicle where bookingdate=?;");
                    p.setString(1, bookingdate.getText().trim());
        }
        else{
            JOptionPane.showMessageDialog(null,"Field empty or Improper Selection");
        }
        
        ResultSet res=p.executeQuery();
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
             
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookingdate;
    private javax.swing.JTextField bookingtime;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deptid;
    private javax.swing.JTextField destination;
    private javax.swing.JTextField driverstaffid;
    private javax.swing.JTextField formno;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField purpose;
    private javax.swing.JButton search;
    private javax.swing.JTextField staffid;
    private javax.swing.JButton update;
    private javax.swing.JTextField vehicleno;
    private javax.swing.JButton viewDriverdetail;
    private javax.swing.JButton viewRegisteredform;
    private javax.swing.JButton viewVehicledetail;
    // End of variables declaration//GEN-END:variables
}
