
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import static javafx.scene.paint.Color.color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */

public class TripCompletionForm extends javax.swing.JFrame {

    /**
     * Creates new form TripCompletionForm
     */
    Connection con=null;
    JComboBox jComboBox1=null;
    public TripCompletionForm() {
        try{
            jComboBox1=new JComboBox();
            jComboBox1.setBounds(200, 330, 175, 25);
        jComboBox1.addItem("Form No");
        jComboBox1.addItem("UH credit card no");
       // jComboBox1.addItem("Booking Date");
        add(jComboBox1);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        formno = new javax.swing.JTextField();
        odometerstart = new javax.swing.JTextField();
        odometerend = new javax.swing.JTextField();
        fuelliter = new javax.swing.JTextField();
        uhcreditcardno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        View = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        complain = new javax.swing.JTextArea();
        close = new javax.swing.JButton();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("form No");

        jLabel2.setText("odometer start");

        jLabel3.setText("Odometer End");

        jLabel4.setText("Fuel Liter");

        jLabel5.setText("UH Credit Card No");

        jLabel6.setText("Complain");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Trip Completion Form");

        insert.setText("insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        View.setText("view completed trips");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        update.setText("update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        complain.setColumns(20);
        complain.setRows(5);
        jScrollPane2.setViewportView(complain);

        close.setText("close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(formno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odometerstart, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(odometerend)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uhcreditcardno, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fuelliter))
                                .addGap(226, 226, 226)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insert)
                        .addGap(38, 38, 38)
                        .addComponent(View)
                        .addGap(36, 36, 36)
                        .addComponent(update)
                        .addGap(45, 45, 45)
                        .addComponent(delete)
                        .addGap(31, 31, 31)
                        .addComponent(close)
                        .addGap(59, 59, 59)
                        .addComponent(search)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(formno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(odometerstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(odometerend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fuelliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(uhcreditcardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(View)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(close)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        try{int r=0,r1=0;
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(formno.getText().trim().length()>0&&odometerstart.getText().trim().length()>0&&odometerend.getText().trim().length()>0&&fuelliter.getText().trim().length()>0&&uhcreditcardno.getText().trim().length()>0&&complain.getText().trim().length()>0)
            {      
            PreparedStatement p=con.prepareStatement("insert into tripcompletion (formno,odometerstar,odometerend,fuel,uhcreditcardno,complain) values(?,?,?,?,?,?);");
            p.setString(1,formno.getText().trim());
            p.setString(2,odometerstart.getText().trim());
            p.setString(3,odometerend.getText().trim());
            p.setString(4,fuelliter.getText().trim());
            p.setString(5,uhcreditcardno.getText().trim());
            p.setString(6,complain.getText().trim());
            r=p.executeUpdate();
            PreparedStatement pchk1=con.prepareStatement("Select * from vehicle where registrationno=?;");
            String s=JOptionPane.showInputDialog( "enter vehicle id");
            pchk1.setString(1,s.trim());
            ResultSet rs1=pchk1.executeQuery();
            if(rs1.next())
            {
                /*s=rs1.getString("booked");
                value=Integer.parseInt(s);
                value--;
                s=Integer.toString(value);*/
             
             PreparedStatement p1=con.prepareStatement("update vehicle set booked=0 where registrationno=?");
            p1.setString(1,s.trim());
            
            r1=p1.executeUpdate();
            if(r1>0)
                JOptionPane.showMessageDialog(null, "Successfull update vehicle");
            }
            billCalculate();
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Recheck form");
            }
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull Insert");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_insertActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
         try{
            con=MySqlConnect.ConnectDB();
        Statement s;
             s = con.createStatement();
        ResultSet res=s.executeQuery("Select * from tripcompletion");
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ViewActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            if(formno.getText().trim().length()>0&&odometerstart.getText().trim().length()>0&&odometerend.getText().trim().length()>0&&fuelliter.getText().trim().length()>0&&uhcreditcardno.getText().trim().length()>0&&complain.getText().trim().length()>0)
            {
            PreparedStatement p=con.prepareStatement("update tripcompletion set formno=?,odometerstar=?,odometerend=?,fuel=?,uhcreditcardno=?,complain=? where formno=?;");
            p.setString(6,formno.getText().trim());
            p.setString(1,odometerstart.getText().trim());
            p.setString(2,odometerend.getText().trim());
            p.setString(3,fuelliter.getText().trim());
            p.setString(4,uhcreditcardno.getText().trim());
            p.setString(5,complain.getText().trim());
            int r=p.executeUpdate();
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull update");
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "Recheck form");
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
          try{
            con=MySqlConnect.ConnectDB();
            PreparedStatement p=null;
        if(jComboBox1.getSelectedItem().equals("Form No")&&formno.getText().trim().length()>0)
        {
                    p=con.prepareStatement("Select * from tripcompletion where formno=?;");
                    p.setString(1, formno.getText().trim());
        }
        else if(jComboBox1.getSelectedItem().equals("UH credit card no")&&uhcreditcardno.getText().trim().length()>0)
        {
                    p=con.prepareStatement("Select * from tripcompletion where uhcreditcardno=?;");
                    p.setString(1, uhcreditcardno.getText().trim());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Field Empty or Improper CheckBox Selected");
        }
        
        ResultSet res=p.executeQuery();
        //get meta data
             ResultSetMetaData rsmetadata= (ResultSetMetaData) res.getMetaData();
             // get column count
             int column=rsmetadata.getColumnCount();
             // this object pass data into jtable
             DefaultTableModel dtm= new DefaultTableModel();
             Vector columnname= new Vector();
             Vector datarow= new Vector();
             for(int i=1;i<=column;i++)
             {
                 columnname.addElement(rsmetadata.getColumnName(i));
             }
             dtm.setColumnIdentifiers(columnname);
             while(res.next())
                     {
                         datarow= new Vector();
                      for(int j=1;j<=column;j++)
                      {
                          datarow.addElement(res.getString(j));
                      }
                      dtm.addRow(datarow);
                     }
             jTable1.setModel(dtm);
             
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            con=MySqlConnect.ConnectDB();
            //insert into deaprtment
            PreparedStatement p=con.prepareStatement("delete from tripcompletion where formno=?;");
            p.setString(1,formno.getText().trim());
            int r=p.executeUpdate();
            if(r>0)
            JOptionPane.showMessageDialog(null, "Successfull delete");
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteActionPerformed
    public void billCalculate()
    {
      try{int r=0,r1=0;
            String s="",dept=""; 
            double d1=0,d2=0,amt=0;
            int a,b;
            con=MySqlConnect.ConnectDB();
            //check vehicle availability
            PreparedStatement pchk=con.prepareStatement("Select * from bill where deptid=?;");
            dept=JOptionPane.showInputDialog("Enter deptid for billing");
            pchk.setString(1,dept);
            ResultSet rs=pchk.executeQuery();
            if(rs.next())
            {
                s=rs.getString("amount");
                d1=Double.parseDouble(s);
                s=JOptionPane.showInputDialog("Enter fuel rate");
                d2=Double.parseDouble(s);
                a=Integer.parseInt(odometerstart.getText().trim());
                b=Integer.parseInt(odometerend.getText().trim());
                amt=d1+(d2*(b-a));
                PreparedStatement p1=con.prepareStatement("update bill set amount=? where deptid=?;");
                p1.setString(1,Double.toString(amt));
                p1.setString(2, dept.trim());
                r1=p1.executeUpdate();
                JOptionPane.showMessageDialog(null, "bill updated");
            }
      }
      catch(Exception e)
      {
          
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TripCompletionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TripCompletionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TripCompletionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TripCompletionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TripCompletionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JButton close;
    private javax.swing.JTextArea complain;
    private javax.swing.JButton delete;
    private javax.swing.JTextField formno;
    private javax.swing.JTextField fuelliter;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField odometerend;
    private javax.swing.JTextField odometerstart;
    private javax.swing.JButton search;
    private javax.swing.JTextField uhcreditcardno;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
